# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=7)),
                ('title', models.CharField(max_length=50)),
                ('startdate', models.DateField(blank=True)),
                ('enddate', models.DateField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.CoursePage')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=500)),
                ('office', models.CharField(blank=True, max_length=500)),
                ('residence', models.CharField(blank=True, max_length=500)),
                ('education', models.CharField(blank=True, max_length=500)),
                ('workexp', models.CharField(blank=True, max_length=500)),
                ('research', models.CharField(blank=True, max_length=500)),
                ('courses', models.IntegerField(default=0)),
                ('active_courses', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
