# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Odd'), (2, 'Even')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='enddate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='startdate',
            field=models.TextField(blank=True),
        ),
    ]
