# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171111_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
