# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171118_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enddate',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='startdate',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
