# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_course_coursepage_coursesubpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='content',
            field=models.TextField(),
        ),
    ]
