# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.IntegerField(default=0),
        ),
    ]
