# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20171114_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
