# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20171119_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='copi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='endyear',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='startyear',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
