# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_profile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='active_courses',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
