# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='publications',
            field=models.IntegerField(default=0),
        ),
    ]
