# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20171128_2008'),
        ('portal', '0009_querymodel'),
    ]

    operations = [
    ]
