# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_merge_20171129_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='1.jpg', upload_to=''),
        ),
    ]
