# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_merge_20171129_0327'),
        ('portal', '0012_merge_20171129_0432'),
    ]

    operations = [
    ]
