# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_merge_20171129_0620'),
        ('portal', '0012_merge_20171129_0442'),
    ]

    operations = [
    ]
