# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_merge_20171129_0620'),
        ('portal', '0013_auto_20171129_0516'),
    ]

    operations = [
    ]
