# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20171129_0813'),
        ('portal', '0014_auto_20171129_0745'),
        ('portal', '0013_auto_20171129_0516'),
    ]

    operations = [
    ]
